global:
  instanceName: test-instance
  integrations:
    - bluetoothLowEnergy
    - espresense
entities:
  behaviors:
    debounced_entity:
      debounce:
        wait: 0.75
        maxWait: 2
    leading_debounced_entity:
      debounce:
        wait: 0.75
        maxWait: 2
        leading: true
        trailing: false
    rolling_average_entity:
      rollingAverage:
        window: 60
    chained_entity:
      debounce:
        wait: 0.75
        maxWait: 2
      rollingAverage:
        window: 60
gpio:
  binarySensors:
    - name: PIR Sensor
      pin: 23
    - name: Radar
      pin: 24
      deviceClass: motion
  switches:
    - name: Test Switch
      pin: 17
shell:
  sensors:
    - name: Simple Test
      command: echo test
      cron: '* * * * *'
    - name: Regex Test
      command: echo 'test 123'
      cron: '* * * * */2'
      regex: '[1-9]+'
      deviceClass: 'timestamp'
      icon: 'mdi:test'
      unitOfMeasurement: 'tests'
  switches:
    - name: Test Switch
      onCommand: echo on
      offCommand: echo off
espresense:
